/***************************************************************************************************************
                                                    GRUPO #1
***************************************************************************************************************/

CREATE TABLE CATEGORIA (
    ID_CATEGORIA   INTEGER NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL
);

ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( ID_CATEGORIA );

CREATE TABLE ENVIOS (
    ID_ENVIO            INTEGER NOT NULL,
    DESC_ENVIO          VARCHAR2(100) NOT NULL,
    DIRE_ENVIO          VARCHAR2(100) NOT NULL,
    SALIDAS_ID_SALIDAS  INTEGER NOT NULL
);

ALTER TABLE ENVIOS ADD CONSTRAINT ENVIOS_PK PRIMARY KEY ( ID_ENVIO );

CREATE TABLE INGRESOS (
    ID_INGRESO                  INTEGER NOT NULL,
    CANT_INGRESADA              INTEGER NOT NULL,
    CONSTO_UNIDAD               NUMBER NOT NULL,
    PROVEEDOR_ID_PROVEEDOR      INTEGER NOT NULL,
    PRODUCTO_COD_PRODUCTO       INTEGER NOT NULL,
    FECHA_INGRESO                DATE NOT NULL
);

ALTER TABLE INGRESOS ADD CONSTRAINT INGRESOS_PK PRIMARY KEY ( ID_INGRESO );

CREATE TABLE PRODUCTO (
    CODIGO_PRODUCTO          INTEGER NOT NULL,
    NOMBRE_PROD              VARCHAR2(50) NOT NULL,
    CANTIDAD_EXIS            INTEGER NOT NULL,
    PRECIO_U                 NUMBER NOT NULL,
    CATEGORIA_ID_CATEGORIA   INTEGER NOT NULL
);

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY ( CODIGO_PRODUCTO );

CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR        INTEGER NOT NULL,
    NOMBRE_PROVEEDOR    VARCHAR2(100) NOT NULL,
    DIRECCION           VARCHAR2(100) NOT NULL,
    NIT_PROVEEDOR       NUMBER NOT NULL
);

ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY ( ID_PROVEEDOR );

CREATE TABLE SALIDAS (
    ID_SALIDA                   INTEGER NOT NULL,
    DEFINICION                  VARCHAR2(100),
    CANTIDAD                    INTEGER NOT NULL,
    PRODUCTO_COD_PRODUCTO       INTEGER NOT NULL,
    FECHA_SALIDA                DATE    NOT NULL
);

ALTER TABLE SALIDAS ADD CONSTRAINT SALIDAS_PK PRIMARY KEY ( ID_SALIDA );

ALTER TABLE ENVIOS
    ADD CONSTRAINT ENVIOS_SALIDAS_FK FOREIGN KEY ( SALIDAS_ID_SALIDAS )
        REFERENCES SALIDAS ( ID_SALIDA );

ALTER TABLE INGRESOS
    ADD CONSTRAINT INGRESOS_PRODUCTO_FK FOREIGN KEY ( PRODUCTO_COD_PRODUCTO )
        REFERENCES PRODUCTO ( CODIGO_PRODUCTO );

ALTER TABLE INGRESOS
    ADD CONSTRAINT INGRESOS_PROVEEDOR_FK FOREIGN KEY ( PROVEEDOR_ID_PROVEEDOR )
        REFERENCES PROVEEDOR ( ID_PROVEEDOR );

ALTER TABLE PRODUCTO
    ADD CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY ( CATEGORIA_ID_CATEGORIA )
        REFERENCES CATEGORIA ( ID_CATEGORIA );

ALTER TABLE SALIDAS 
    ADD CONSTRAINT SALIDAS_PRODUCTO_FK FOREIGN KEY ( PRODUCTO_COD_PRODUCTO )
        REFERENCES PRODUCTO ( CODIGO_PRODUCTO );